name: Mac Test

on:
  push:
    branches:
      - master
jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: submodules-init
      uses: snickerbockers/submodules-init@v4
    - name: update brew
      run:  brew tap jmuncaster/homebrew-header-only
    - name: install packages
      run:  brew install autogen autoconf automake binutils coreutils cmake ldns expat xz doxygen hidapi graphviz libpgm libunwind-headers unbound zmq czmq jmuncaster/header-only/cppzmq zeromq libsodium miniupnpc openssl pkg-config protobuf readline
    - name: install boost
      run:  |
          curl -L -o boost_1_72_0.tar.gz https://sourceforge.net/projects/boost/files/boost/1.72.0/boost_1_72_0.tar.gz/download 
          tar -xf boost_1_72_0.tar.gz
          cd boost_1_72_0
          ./bootstrap.sh
          ./b2 headers
          sudo ./b2 cxxflags=-fPIC cflags=-fPIC -a link=static threading=multi threadapi=pthread install
    - name: install protobuf
      run: |
        cd external
        sudo chmod +x install_protobuf_dep_macos.sh
        sudo ./install_protobuf_dep_macos.sh
    - name: test
      run: make release-test
